default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: journal_2_dev

test:
  <<: *default
  database: journal_2_test

production:
  <<: *default
  database: journal_2_prod
